name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    env:
      # Customize this
      IMAGE_NAME: nginx              
      VERSION: v1                     
      REPO_URL: https://github.com/jagadamma/3tier.git

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build Docker Image
        run: |
          cd client
          docker build -t ${IMAGE_NAME}:${VERSION} .

      - name: Tag Docker Image
        run: |
          docker tag ${IMAGE_NAME}:${VERSION} ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}

 
      - name: Clone 3tier Repo
        run: |
          git clone -b master https://${{ secrets.PAT_TOKEN }}@github.com/jagadamma/3tier.git


      - name: Update frontend & backend image in YAML
        run: |
          cd 3tier

          # Update backend image inside backend.yml
          sed -i "s#image: .*#image: ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}#g" backend.yml

          # Update frontend image inside frontend-deployment.yaml
          sed -i "s#image: .*#image: ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}#g" frontend-deployment.yaml

      - name: Commit & Push Changes to 3tier
        run: |
          cd 3tier
          git config --global user.email "abilashp.unni@gmail.com"
          git config --global user.name "jagadamma"
          git add backend.yml frontend-deployment.yaml
          git commit -m "Update image to ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/jagadamma/3tier.git
